export const COURSE_ADD_BEGIN = "COURSE_ADD_BEGIN";
export const COURSE_ADD_SUCCESS = "COURSE_ADD_SUCCESS";
export const COURSE_ADD_ERROR = "COURSE_ADD_ERROR";

export const COURSE_FETCH_BEGIN = "COURSE_FETCH_BEGIN";
export const COURSE_FETCH_SUCCESS = "COURSE_FETCH_SUCCESS";
export const COURSE_FETCH_ERROR = "COURSE_FETCH_ERROR";
